data<-read.table("household_power_consumption.txt",sep=";",header=TRUE,colClasses=c("Date"="character"),stringsAsFactors=FALSE)
data<-subset(data,Date == "1/2/2007" | Date == "2/2/2007")
data<-transform(data,Global_active_power=as.numeric(Global_active_power),Sub_metering_1=as.numeric(Sub_metering_1),Sub_metering_2=as.numeric(Sub_metering_2),Sub_metering_3=as.numeric(Sub_metering_3))
datetime <- strptime(paste(data$Date, data$Time, sep=" "), "%d/%m/%Y %H:%M:%S")
with(data,plot(datetime,type="l",Sub_metering_1,ylab="Energy sub metering"),col="black")
points(datetime,data$Sub_metering_2,col="red",type="l")
points(datetime,data$Sub_metering_3,col="blue",type="l")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, lwd=2.5, col=c("black", "red", "blue"))
dev.copy(png,'plot3.png',bg="red")
dev.off()